### ISSUE TITLE
Register error

### ISSUE THREAD

**Issue by Mitra-Electronics** [Aafiya-H/Classroom#46]
Whenever I am trying to sign up, It is showing

`OperationalError at /register/
no such table: custom_user`

Try to migrate the database

**Comment by Aafiya-H** [comment]
Please clone the repository and make migrations locally.

**Comment by Mitra-Electronics** [comment]
I know that, I have made the migrations locally but on your heroku environment it is showing an error

**Comment by talha1503** [comment]
I'd suggest you to watch the following tutorial: https://www.youtube.com/watch?v=UkokhawLKDU

**Comment by Mitra-Electronics** [comment]
Ok, thanks
